bloggerscommune/blog_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'blog_app'

urlpatterns =[
    path(r'about/',views.AboutView.as_view(),name= 'about'),
    path(r'', views.BlogPostListView.as_view(),name = 'blogpost_list'),
    path('blogpost/<int:pk>/', views.BlogPostDetailView.as_view(),name = 'blogpost_detail'),
    path('blogpost/create/',views.BlogPostCreateView.as_view(),name ='blogpost_create'),
    path('blogpost/<int:pk>/edit/', views.BlogPostUpdateView.as_view(),name = 'blogpost_edit'),
    path('blogpost/<int:pk>/delete/', views.BlogPostDeleteView.as_view(),name = 'blogpost_delete'),
    path('drafts/', views.DraftListView.as_view(),name = 'blogpost_draft_list'),
    path('blogpost/<int:pk>/comment/', views.add_comment_to_blogpost,name = 'add_comment_to_blogpost'),
    path('blogpost/<int:pk>/publish/', views.blogpost_publish,name = 'blogpost_publish'),
    path('comment/<int:pk>/approve/', views.comment_approve,name = 'comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remover,name = 'comment_remove'),
    
]

bloggerscommune/bloggerscommune/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [
    # path('login/', LoginView.as_view(template_name='registration/login.html'), name="login"),
    # path('logout/', LogoutView.as_view(template_name='blog_app/blogpost_list.html'), name="logout"),
    path(r'',include('blog_app.urls')),
    path('user/',include('user_auth_app.urls')),
    path('admin/', admin.site.urls),
]

bloggerscommune/user_auth_app/urls.py
from django.urls import path ,include
from user_auth_app import views

app_name = "user_auth_app"

urlpatterns = [
    path(r'',views.user_auth_index,name = "user_index"),
    path(r'login/',views.user_login,name = "user_login"),
    path(r'register/',views.registration,name = "user_registration"),
    path(r'logout/',views.user_logout,name="user_logout"),

]

bloggerscommune/templates/index.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/blog_app.css'%}">


        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
        <link href="https://fonts.googleapis.com/css?family=Volkhov&display=swap" rel="stylesheet">
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
            type="text/css" media="screen" charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">




        <!-----yo css for list view html ---------->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"
            id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <!-----yo css for list view html ---------->

        <title>BloggersCommune</title>
        <style>
            body {

                font-family: 'Volkhov', serif;
            }
        </style>
    </head>

    <body>
        <div>
            <nav class="navbar navbar-expand-md navbar navbar-dark bg-dark">
                <a class="navbar-brand" href="#">BloggersCommune</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse w-100 order-4 order-md-0 collapsenav" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'blog_app:blogpost_list'%}">Blog<span
                                    class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Details<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog_app:about' %}">About</a>
                        </li>
                       
                        <li>
                            {%if user.is_authenticated %}
                                    <li class="nav-item dropdown">
                                        
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                    
                                            Actions
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    
                                            <a class="dropdown-item" href="{% url 'blog_app:blogpost_create'%}">Create</a>
                                            <a class="dropdown-item" href="{% url 'blog_app:blogpost_list'%}">Update</a>
                                            <a class="dropdown-item" href="{% url 'blog_app:blogpost_draft_list'%}">Drafts</a>
                                            <a class="dropdown-item" href="{% url 'blog_app:blogpost_list'%}">Delete</a>
                                    
                                    
                                            <div class="dropdown-divider">
                                    
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user_auth_app:user_logout' %}">Logout</a>
                                    </li>
                                    <li>

                                            <li class="form-inline my-2 my-lg-0">
                                                <a style="color:whitesmoke">Welcome {{user.username}}</a>
                                            </li>
                                    </li>
                            {%else%}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'user_auth_app:user_registration' %}">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'user_auth_app:user_login' %}">Login</a>
                                </li>
                            
                            
                            {% endif %}
                        </li>
                        

                      
                       

                    </ul>


                    <div></div>



                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

                    </form>



                </div>
            </nav>


        </div>


        {% block index_block %}

        {% endblock %}



    </body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}">
    </script>
    <script src="{% static 'js/blog_app.js'%}">
    </script>

</html>