bloggerscommune/blog_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'blog_app'

urlpatterns =[
    path(r'about/',views.AboutView.as_view(),name= 'about'),
    path(r'', views.BlogPostListView.as_view(),name = 'blogpost_list'),
    path('blogpost/<int:pk>/', views.BlogPostDetailView.as_view(),name = 'blogpost_detail'),
    path('blogpost/create/',views.BlogPostCreateView.as_view(),name ='blogpost_create'),
    path('blogpost/<int:pk>/edit/', views.BlogPostUpdateView.as_view(),name = 'blogpost_edit'),
    path('blogpost/<int:pk>/delete/', views.BlogPostDeleteView.as_view(),name = 'blogpost_delete'),
    path('drafts/', views.DraftListView.as_view(),name = 'blogpost_draft_list'),
    path('blogpost/<int:pk>/comment/', views.add_comment_to_blogpost,name = 'add_comment_to_blogpost'),
    path('blogpost/<int:pk>/publish/', views.blogpost_publish,name = 'blogpost_publish'),
    path('comment/<int:pk>/approve/', views.comment_approve,name = 'comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remover,name = 'comment_remove'),
    
]

bloggerscommune/bloggerscommune/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [
    # path('login/', LoginView.as_view(template_name='registration/login.html'), name="login"),
    # path('logout/', LogoutView.as_view(template_name='blog_app/blogpost_list.html'), name="logout"),
    path(r'',include('blog_app.urls')),
    path('user/',include('user_auth_app.urls')),
    path('admin/', admin.site.urls),
]

bloggerscommune/blog_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from user_auth_app.models import UserProfileInfo,User
# from django.conf import settings


# Create your models here.


class BlogPost(models.Model):
    author = models.ForeignKey(UserProfileInfo, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now())
    published_date = models.DateTimeField(blank = True,null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    # def unpublish(self):
    #     self.published_date
    #     self.save()
        
    

    def approve_comments(self):
        return self.comments.filter(approve_comments = True)

    def get_absolute_url(self):
        return reverse("blog_app:blogpost_detail", kwargs={'pk':self.pk})


    def __str__(self):
        return self.title


class CommentOnPost(models.Model):
    comment_post = models.ForeignKey('blog_app.BlogPost',related_name = 'comments', on_delete = models.CASCADE)
    comment_author = models.CharField(max_length = 50)
    comment_text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now())
    approved_comment = models.BooleanField(default = False)


    def approve(self):
        self.approved_comment = True
        self.save()
    

    def get_absolute_url(self):
        return reverse('blogpost_list')

    def __str__(self):
        return self.comment_text

bloggerscommune/blog_app/forms.py
from blog_app.models import BlogPost,CommentOnPost
from django import forms


class BlogPostForm(forms.ModelForm):
    class Meta():
        model = BlogPost
        
        fields = ('author','title','text')

        widgets = {
            
            'title':forms.TextInput(attrs= {'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }
        


class CommentOnPostForm(forms.ModelForm):
    class Meta():
        model = CommentOnPost
        fields = ('comment_author','comment_text')


        widgets = {
            'comment_author':forms.TextInput(attrs= {'class':'textinputclass'}),
            'comment_text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }
        
        

bloggerscommune/blog_app/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView,DetailView,ListView,CreateView,DeleteView,UpdateView)
from blog_app.models import BlogPost,CommentOnPost
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog_app.forms import BlogPostForm,CommentOnPostForm
from django.urls import reverse_lazy

# Create your views here.


class AboutView(TemplateView):
    template_name = 'blog_app/about.html'

class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self):
        return BlogPost.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    context_object_name = "blogpost_list"

class BlogPostDetailView(DetailView):
    model = BlogPost

    
class BlogPostCreateView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = '/blog_app/blogpost_detail.html'
    print("checkpoint1")
    model = BlogPost
    print("checkpoint2")
    form_class = BlogPostForm
    print("checkpoint3")
    
    
    # def form_valid(self, form,inlines):
        
    #     print("checkpoint4")
        

    #     print(type(self.request.user.username))
    #     print("checkpoint0")
    #     print(type(self.request.user))
    #     print(type(BlogPost.author))
    #     form.instance.author=self.request.user
    #     print("checkpoint5")
        
    #     print("checkpoint6")
    #     print(self.request.user)
    #     return super(BlogPostCreateView,self).form_valid(form,inlines)
    


    

class BlogPostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = '/blog_app/blopgpost_detail.html'
    form_class = BlogPostForm
    model = BlogPost

class BlogPostDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/login/'
    success_url = reverse_lazy('blogpost_list')

class DraftListView(LoginRequiredMixin,ListView):
    context_object_name = 'blogpost_draft_list'
    login_url = '/login/'
    redirect_field_name = '/blog_app/blogpost_list.html'
    model = BlogPost
    
    template_name = 'blog_app/blogpost_draft.html'

    def get_queryset(self):
        return BlogPost.objects.filter(published_date__isnull = True).order_by('created_date')


@login_required   
def blogpost_publish(request,pk):
    post = get_object_or_404(BlogPost,pk=pk)
    post.publish()
    return redirect('blog_app:blogpost_detail',pk= pk)


@login_required
def add_comment_to_blogpost(request,pk):
    print('checkpoint 1')

    
    blogpost = get_object_or_404(BlogPost,pk=pk)
    if request.method == "POST":
        print('checkpoint 3')
        form = CommentOnPostForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.comment_post = blogpost
            comment.save()
            
            return redirect('blog_app:blogpost_detail',pk=blogpost.pk)

    else:
        form = CommentOnPostForm()
        print(type(form))
        print('checkpoint 2')
    
    
    return render(request,'blog_app/comment_form.html',{'form':form,'blogpost':blogpost})
@login_required   
def comment_remover(request,pk):
    comment = get_object_or_404(CommentOnPost,pk=pk)
    blogpost_pk = comment.comment_post.pk
    comment.delete()
    return redirect('blog_app:blogpost_detail',pk= blogpost_pk)




@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(CommentOnPost,pk=pk)
    comment.approve()
    return redirect('blog_app:blogpost_detail',pk=comment.comment_post.pk)

bloggerscommune/blog_app/templates/blog_app/about.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}



{%endblock%}

bloggerscommune/blog_app/templates/blog_app/blogpost_confirm_delete.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}

{%endblock%}

bloggerscommune/blog_app/templates/blog_app/blogpost_detail.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}


<div class="container">
    <div class="well">
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="">
            </a>
            <div class="media-body">
                
                    <h4 class="media-heading">{{blogpost.title}}</h4>
               
                <p class="text-right">By {{blogpost.author|capfirst}}</p>
                <p>{{blogpost.text}}</p>
                <ul class="list-inline list-unstyled">
                    <li><span><i class="glyphicon glyphicon-calendar"></i>{{blogpost.published_date}}</span></li>
                    <li>|</li>
                    <span>
                        <i class="glyphicon glyphicon-comment"></i>
                        <a href="{%url 'blog_app:add_comment_to_blogpost' pk=blogpost.pk%}" style="color:inherit;">
                            {{blogpost.approved_comment.count}} comments
                            
                        </a>
                    
                    </span>
                    <li>|</li>
                    <li>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </li>
                    <li>|</li>
                    <li>

                        <span><i class="fa fa-facebook-square"></i></span>
                        <span><i class="fa fa-twitter-square"></i></span>
                        <span><i class="fa fa-google-plus-square"></i></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="well">

            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">Comments </h4>
                        <ul class="list-inline list-unstyled">
                            {%for comment in blogpost.comments.all %}
                                {%if user.is_authenticated or comment.approved_comment %}
                                
                                    {%if not comment.approved_comment and blogpost.author.user.username == request.user.username%}
                                        <p>{{comment.comment_text}}</p><br />
                                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{comment.created_date}}</span></li>
                                        <li>|</li>
                                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{comment.comment_author}}</span></li>
                                        <li>|</li>
                                        
                                        
                                        <a href="{%url 'blog_app:comment_approve' pk=comment.pk%}" class="btn btn-primary">
                                            <span>Approve</span>
                                        </a>
                                        <a href="{%url 'blog_app:comment_remove' pk=comment.pk%}" class="btn btn-primary">
                                            Delete
                                        </a>
                                    
                                    {%else%}
                                        <p>{{comment.comment_text}}</p><br />
                                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{comment.created_date}}</span></li>
                                        <li>|</li>
                                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{comment.comment_autor}}</span></li>
                                        <li>|</li>
                                        
                                    {%endif%}
                                
                                
                                {%endif%}
                            {%endfor%}
                            
                            
                            

                    </ul>

                   



                </div>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="well">
            {%block detail_block%}
            
            
            {%endblock%}
        </div>
    </div>


</div>




{%endblock%}

bloggerscommune/blog_app/templates/blog_app/blogpost_draft.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}
<ol></ol>
{%for items in blogpost_draft_list %}
<div class="container">
    <div class="well">
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="">
            </a>
            <div class="media-body">
                
                {% if items.author.user.username == request.user.username  %}
                    <h1>broooo</h1>
                
                    <a href="{%url 'blog_app:blogpost_detail' pk=items.pk%}" style="color:inherit;">
                        <h4 class="media-heading">{{items.title}}</h4>
                    </a>
                    <p class="text-right">By {{items.author|capfirst}}</p>
                    <p>{{items.text|truncatechars:200}}</p>
                    <ul class="list-inline list-unstyled">
                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{items.published_date}}</span></li>
                        <li>|</li>
                    
                        <li>|</li>
                        <li>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                        </li>
                        <li>|</li>
                        <li>
                    
                            <span><i class="fa fa-facebook-square"></i></span>
                            <span><i class="fa fa-twitter-square"></i></span>
                            <span><i class="fa fa-google-plus-square"></i></span>
                        </li>
                    </ul>
                <a href="{%url 'blog_app:blogpost_edit' pk=items.pk%}" class="btn btn-primary">
                    <li><span><i class="glyphicon glyphicon-pencil"></i>Edit</span></li>
                </a>
                {% if blogpost.published_date == null%}
                <a href="{%url 'blog_app:blogpost_publish' pk=items.pk%}" class="btn btn-primary">
                    <li><span><i class="glyphicon glyphicon-publish"></i>Publish</span></li>
                </a>
                {%endif%}
                <a href="{%url 'blog_app:blogpost_delete' pk=items.pk%}" class="btn btn-primary">
                    <li><span><i class="glyphicon glyphicon-remove"></i>Delete</span></li>
                </a>
                
                
                
                
                {%endif%}
               
            </div>
        </div>
    </div>
</div>

{%endfor%}
{%endblock%}

bloggerscommune/blog_app/templates/blog_app/blogpost_form.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}
    <div class="container">
        <div class="well">
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="">
                </a>
                <div class="media-body">
                    <h1>Create new blog</h1>
                    <form method="post" >
                        {%csrf_token%}
                        {{form.as_p}}

                        
                    
                        <input type="submit" class="btn btn-primary" value="Submit">
                    
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
   




{%endblock%}

bloggerscommune/blog_app/templates/blog_app/blogpost_list.html
<!DOCTYPE html>
{% extends 'index.html'  %}
{% block index_block %}
    <ol></ol>
    {%for items in blogpost_list %}
    <div class="container">
        <div class="well">
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="">
                </a>
                <div class="media-body">
                    <a  href="{%url 'blog_app:blogpost_detail' pk=items.pk%}" style="color:inherit;">
                        <h4 class="media-heading">{{items.title}}</h4>
                    </a>
                    <p class="text-right">By {{items.author|capfirst}}</p>
                    <p>{{items.text|truncatechars:200}}</p>
                    <ul class="list-inline list-unstyled">
                        <li><span><i class="glyphicon glyphicon-calendar"></i>{{items.published_date}}</span></li>
                        <li>|</li>
                        <span>
                            <i class="glyphicon glyphicon-comment"></i>
                            <a href="{%url 'blog_app:add_comment_to_blogpost' pk=items.pk%}" style="color:inherit;">
                                {{items.approved_comment.count}} comments
                            </a>
                             
                        </span>
                        <li>|</li>
                        <li>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                        </li>
                        <li>|</li>
                        <li>
                            
                            <span><i class="fa fa-facebook-square"></i></span>
                            <span><i class="fa fa-twitter-square"></i></span>
                            <span><i class="fa fa-google-plus-square"></i></span>
                        </li>


                        

                    </ul>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}
    {%block list_block%}
    
    {%endblock%}
{%endblock%}

bloggerscommune/blog_app/templates/blog_app/comment_form.html
<!DOCTYPE html>
{% extends 'blog_app/blogpost_detail.html' %}
{% block detail_block %}
    <form method="POST" >
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Submit">

    </form>


{%endblock%}